
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA LBRACKET LPAREN NUMBER PIVOT RBRACKET RPAREN SPACEpartida : PIVOTpartida : carta_c SPACE partida SPACE carta_c\n               | carta_p SPACE partida SPACE carta_p\n               | carta_v SPACE partida SPACE carta_v\n               | carta_r SPACE partida SPACE carta_r\n               | carta_a SPACE partida SPACE carta_acarta_c : LBRACKET LPAREN NUMBER RPAREN COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER RBRACKETcarta_p : LBRACKET NUMBER COMMA SPACE LPAREN NUMBER RPAREN COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER RBRACKETcarta_v : LBRACKET NUMBER COMMA SPACE NUMBER COMMA SPACE LPAREN NUMBER RPAREN COMMA SPACE NUMBER COMMA SPACE NUMBER RBRACKETcarta_r : LBRACKET NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE LPAREN NUMBER RPAREN COMMA SPACE NUMBER RBRACKETcarta_a : LBRACKET NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE LPAREN NUMBER RPAREN RBRACKET'
    
_lr_action_items = {'PIVOT':([0,9,10,11,12,13,],[2,2,2,2,2,2,]),'LBRACKET':([0,9,10,11,12,13,23,24,25,26,27,],[8,8,8,8,8,8,31,33,35,37,39,]),'$end':([1,2,30,32,34,36,38,118,119,120,121,122,],[0,-1,-2,-3,-4,-5,-6,-7,-11,-10,-9,-8,]),'SPACE':([2,3,4,5,6,7,16,17,18,19,20,22,30,32,34,36,38,40,48,50,51,52,53,61,64,69,72,73,74,82,85,86,90,94,95,103,105,106,107,118,119,120,121,122,],[-1,9,10,11,12,13,23,24,25,26,27,29,-2,-3,-4,-5,-6,47,55,57,58,59,60,68,71,76,79,80,81,89,92,93,97,101,102,108,110,111,112,-7,-11,-10,-9,-8,]),'LPAREN':([8,29,31,55,57,76,79,97,101,],[14,42,14,63,42,84,63,104,84,]),'NUMBER':([8,14,29,33,35,37,39,42,47,55,58,59,60,63,68,71,76,80,81,84,89,92,93,102,104,108,110,111,112,],[15,21,41,43,44,45,46,49,54,62,65,66,67,70,75,78,83,87,88,91,96,99,100,83,109,113,115,116,117,]),'COMMA':([15,28,41,43,44,45,46,54,56,62,65,66,67,75,77,78,83,87,88,96,98,99,100,],[22,40,48,50,51,52,53,61,64,69,72,73,74,82,85,86,90,94,95,103,105,106,107,]),'RPAREN':([21,49,70,91,109,],[28,56,77,98,114,]),'RBRACKET':([113,114,115,116,117,],[118,119,120,121,122,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'partida':([0,9,10,11,12,13,],[1,16,17,18,19,20,]),'carta_c':([0,9,10,11,12,13,23,],[3,3,3,3,3,3,30,]),'carta_p':([0,9,10,11,12,13,24,],[4,4,4,4,4,4,32,]),'carta_v':([0,9,10,11,12,13,25,],[5,5,5,5,5,5,34,]),'carta_r':([0,9,10,11,12,13,26,],[6,6,6,6,6,6,36,]),'carta_a':([0,9,10,11,12,13,27,],[7,7,7,7,7,7,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> partida","S'",1,None,None,None),
  ('partida -> PIVOT','partida',1,'p_partida_base','super_trunfo.py',66),
  ('partida -> carta_c SPACE partida SPACE carta_c','partida',5,'p_partida_recursiva','super_trunfo.py',73),
  ('partida -> carta_p SPACE partida SPACE carta_p','partida',5,'p_partida_recursiva','super_trunfo.py',74),
  ('partida -> carta_v SPACE partida SPACE carta_v','partida',5,'p_partida_recursiva','super_trunfo.py',75),
  ('partida -> carta_r SPACE partida SPACE carta_r','partida',5,'p_partida_recursiva','super_trunfo.py',76),
  ('partida -> carta_a SPACE partida SPACE carta_a','partida',5,'p_partida_recursiva','super_trunfo.py',77),
  ('carta_c -> LBRACKET LPAREN NUMBER RPAREN COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER RBRACKET','carta_c',17,'p_carta_comprimento','super_trunfo.py',111),
  ('carta_p -> LBRACKET NUMBER COMMA SPACE LPAREN NUMBER RPAREN COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER RBRACKET','carta_p',17,'p_carta_peso','super_trunfo.py',117),
  ('carta_v -> LBRACKET NUMBER COMMA SPACE NUMBER COMMA SPACE LPAREN NUMBER RPAREN COMMA SPACE NUMBER COMMA SPACE NUMBER RBRACKET','carta_v',17,'p_carta_velocidade','super_trunfo.py',122),
  ('carta_r -> LBRACKET NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE LPAREN NUMBER RPAREN COMMA SPACE NUMBER RBRACKET','carta_r',17,'p_carta_risco','super_trunfo.py',127),
  ('carta_a -> LBRACKET NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE NUMBER COMMA SPACE LPAREN NUMBER RPAREN RBRACKET','carta_a',17,'p_carta_agressividade','super_trunfo.py',132),
]
